version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    container_name: migrate
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app/src/db/migrations
    command: >
      sh -c "
      if [ ! -f .src/db/migrations/.init_done ]; then
        aerich init -t src.settings.TORTOISE_ORM --location src.db/migrations &&
        aerich init-db &&
        touch .src/db/migrations/.init_done;
      fi &&
      aerich migrate &&
      aerich upgrade"

  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      while ! pg_isready -h db -p 5432 -q; do
        echo 'Waiting for database...'
        sleep 1;
      done &&
      python3 main.py"