services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "23556:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      until nc -z -v -w 30 db 5432; do
        echo 'Waiting for database...';
        sleep 1;
      done &&
      python main.py"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/postgres/postgres-data
