version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "23556:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /home/osi/postgres-data:/var/lib/postgresql/data

  migrate:
    container_name: migrate
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      until nc -z -v -w 30 db 5432; do
        echo 'Waiting for database...';
        sleep 1;
      done &&
      if [ ! -f src/db/migrations/.init_done ]; then
        echo 'Running aerich init' &&
        aerich init -t src.settings.TORTOISE_ORM --location src/db/migrations &&
        echo 'Running aerich init-db' &&
        aerich init-db &&
        touch src/db/migrations/.init_done;
      fi &&
      echo 'Running aerich migrate' &&
      aerich migrate &&
      echo 'Running aerich upgrade' &&
      aerich upgrade"

  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      until nc -z -v -w 30 db 5432; do
        echo 'Waiting for database...';
        sleep 1;
      done &&
      python main.py"

volumes:
  postgres-data:
